CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    name  varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean     NOT NULL,
    title  varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations
(
    id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT,
    lon FLOAT
);

CREATE TABLE IF NOT EXISTS events
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         varchar(2000) NOT NULL,
    category_id        bigint REFERENCES categories (id) ON DELETE CASCADE,
    created_on         timestamp without time zone,
    description        varchar(7000) NOT NULL,
    event_date         timestamp without time zone,
    user_id            bigint REFERENCES users (id) ON DELETE CASCADE,
    location_id        bigint REFERENCES locations (id) ON DELETE CASCADE,
    paid               boolean       NOT NULL,
    participant_limit  integer       NOT NULL,
    published_on       timestamp without time zone,
    request_moderation boolean       NOT NULL,
    state              varchar(20)   NOT NULL,
    title              varchar(120)  NOT NULL
);

create table if not exists requests
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     bigint REFERENCES events (id) ON DELETE CASCADE,
    requester_id bigint REFERENCES users (id) ON DELETE CASCADE,
    status       varchar(20) NOT NULL,
    created      timestamp without time zone
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id bigint REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       bigint REFERENCES events (id) ON DELETE CASCADE
);